lists= [1,5,10,54,48,25,65]
print(lists)
print("appending in the list")
lists.append(77)
print(lists)
print("insert function")
lists.insert(0,69)
print(lists)
print("remove function")
lists.remove(69)
print(lists)
print("pop function")
lists.pop()
print(lists)
